### ISSUE TITLE
crabemu crashes on compilinig el capitan 

### ISSUE THREAD

**Issue by Mirppc** [OpenEmu/CrabEmu-Core#1]
in compiling crabemu on osx elcapitan in xcode 7.3 beta i ran into the following issue.

[code](null): error: /Users/~/Documents/OpenEmu/ColecoVision/OEColecoVisionSystemResponderClient.h: No such file or directory
[/code]
  this was the only build error i ran into thus far. if you need to contact me i will be in #dcemuuk on freenode.

**Comment by clobber** [comment]
Follow the compile guide in the wiki. You have not cloned the sub modules.
